apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hello World</title>
    </head>
    <body>
        <body style="background-color: blue;">
        <h1 style="color: white;">Hello World:</h1>
        <h2 style="color: red;">I am Karthi coming as a developer!!</h2>
        <h2 style="color: red;">Welcome to deployment also</h2>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-container
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/local/apache2/htdocs/index.html
      volumes:
      - name: html-volume
        configMap:
          name: html-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
  namespace: default
spec:
  selector:
    app: html-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
  type: LoadBalancer
